name = "imdb-api"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-10-22"
kv_namespaces = [
         { binding = "CACHE", id = "2672b66c4f9142a89ec55f2731dc8b2c" }
]
